[package]
name = "leo-compiler"
version = "1.2.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Compiler of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.leo-ast]
path = "../ast"
version = "1.2.2"

[dependencies.leo-gadgets]
path = "../gadgets"
version = "1.2.2"

[dependencies.leo-grammar]
path = "../grammar"
version = "1.2.2"

[dependencies.leo-imports]
path = "../imports"
version = "1.2.2"

[dependencies.leo-input]
path = "../input"
version = "1.2.2"

[dependencies.leo-package]
path = "../package"
version = "1.2.2"

[dependencies.leo-state]
path = "../state"
version = "1.2.2"

[dependencies.leo-asg]
path = "../asg"
version = "1.2.2"

[dependencies.snarkvm-curves]
version = "0.0.4"
default-features = false

[dependencies.snarkvm-dpc]
version = "0.0.4"
default-features = false

[dependencies.snarkvm-errors]
version = "0.0.4"
default-features = false

[dependencies.snarkvm-gadgets]
version = "0.0.4"
default-features = false

[dependencies.snarkvm-models]
version = "0.0.4"
default-features = false

[dependencies.snarkvm-objects]
version = "0.0.4"
default-features = false

[dependencies.snarkvm-utilities]
version = "0.0.4"

[dependencies.bincode]
version = "1.0"

[dependencies.hex]
version = "0.4.2"

[dependencies.indexmap]
version = "1.6.1"
features = [ "serde-1" ]

[dependencies.pest]
version = "2.0"

[dependencies.rand]
version = "0.7"

[dependencies.rand_xorshift]
version = "0.2"
default-features = false

[dependencies.serde]
version = "1.0"

[dependencies.sha2]
version = "=0.9.0"

[dependencies.thiserror]
version = "1.0"

[dependencies.tracing]
version = "0.1"

[dependencies.uuid]
version = "0.8"
features = [ "v4", "serde" ]

[dev-dependencies.num-bigint]
version = "0.3"

[dev-dependencies.snarkvm-algorithms]
version = "0.0.4"
default-features = false

[features]
default = [ ]
ci_skip = [ "leo-grammar/ci_skip", "leo-ast/ci_skip" ]
